// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: schema.proto

package example

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldOne      []*RepeatedMessage     `protobuf:"bytes,1,rep,name=field_one,json=fieldOne,proto3" json:"field_one,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetFieldOne() []*RepeatedMessage {
	if x != nil {
		return x.FieldOne
	}
	return nil
}

type RepeatedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldTwo      map[string]uint32      `protobuf:"bytes,1,rep,name=field_two,json=fieldTwo,proto3" json:"field_two,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	FieldThree    string                 `protobuf:"bytes,2,opt,name=field_three,json=fieldThree,proto3" json:"field_three,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatedMessage) Reset() {
	*x = RepeatedMessage{}
	mi := &file_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedMessage) ProtoMessage() {}

func (x *RepeatedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedMessage.ProtoReflect.Descriptor instead.
func (*RepeatedMessage) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{1}
}

func (x *RepeatedMessage) GetFieldTwo() map[string]uint32 {
	if x != nil {
		return x.FieldTwo
	}
	return nil
}

func (x *RepeatedMessage) GetFieldThree() string {
	if x != nil {
		return x.FieldThree
	}
	return ""
}

var File_schema_proto protoreflect.FileDescriptor

const file_schema_proto_rawDesc = "" +
	"\n" +
	"\fschema.proto\x12\aexample\x1a\x1fgoogle/api/field_behavior.proto\"@\n" +
	"\aMessage\x125\n" +
	"\tfield_one\x18\x01 \x03(\v2\x18.example.RepeatedMessageR\bfieldOne\"\xb9\x01\n" +
	"\x0fRepeatedMessage\x12C\n" +
	"\tfield_two\x18\x01 \x03(\v2&.example.RepeatedMessage.FieldTwoEntryR\bfieldTwo\x12$\n" +
	"\vfield_three\x18\x02 \x01(\tB\x03\xe0A\x03R\n" +
	"fieldThree\x1a;\n" +
	"\rFieldTwoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01B\xa4\x01\n" +
	"\vcom.exampleB\vSchemaProtoP\x01ZLgithub.com/joeycumines-scw/protobuf-es-bug-map-key-length/go/example;example\xa2\x02\x03EXX\xaa\x02\aExample\xca\x02\aExample\xe2\x02\x13Example\\GPBMetadata\xea\x02\aExampleb\x06proto3"

var (
	file_schema_proto_rawDescOnce sync.Once
	file_schema_proto_rawDescData []byte
)

func file_schema_proto_rawDescGZIP() []byte {
	file_schema_proto_rawDescOnce.Do(func() {
		file_schema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schema_proto_rawDesc), len(file_schema_proto_rawDesc)))
	})
	return file_schema_proto_rawDescData
}

var file_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_schema_proto_goTypes = []any{
	(*Message)(nil),         // 0: example.Message
	(*RepeatedMessage)(nil), // 1: example.RepeatedMessage
	nil,                     // 2: example.RepeatedMessage.FieldTwoEntry
}
var file_schema_proto_depIdxs = []int32{
	1, // 0: example.Message.field_one:type_name -> example.RepeatedMessage
	2, // 1: example.RepeatedMessage.field_two:type_name -> example.RepeatedMessage.FieldTwoEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_schema_proto_init() }
func file_schema_proto_init() {
	if File_schema_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schema_proto_rawDesc), len(file_schema_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_proto_goTypes,
		DependencyIndexes: file_schema_proto_depIdxs,
		MessageInfos:      file_schema_proto_msgTypes,
	}.Build()
	File_schema_proto = out.File
	file_schema_proto_goTypes = nil
	file_schema_proto_depIdxs = nil
}
